apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: default
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP